---
title: "Aus_species_distributions"
author: "Samuel Andrew"
date: "4 April 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r run the test models, echo=TRUE, eval=FALSE}
#rm(list= ls())
#== 1. packages
library(cmsdm)
library(BIENWorkflow)
library(trinaryMaps)
library(raster)
library(sp)

## Make the custom background files automatically copy in sdmdirectories
myInputDir="D:/Documents_2/SD_work/Aus_BIEN4_test"
myModelingDir="D:/Documents_2/SD_work/Aus_BIEN4_test/BIEN_v1"
if(!file.exists(myModelingDir)) dir.create(myModelingDir)

#== 2. Create directories
runName='Aus_demo_180412'

# system specific
baseDir=paste0(myModelingDir,'/', runName,'_inputs')
mySpeciesDir=paste0(myInputDir,'/Pres_Species')
myCustomBackgroundDir=paste0(myInputDir,'/Pres_Family')
myCustomBackgroundTable= paste0(myInputDir,'/Scripts/Aus_lookup_Table.csv')
myEnvDir=paste0(myInputDir,'/Climate_data_final')
# each of these should be stored as a single stack
#myOtherEnvDir=NULL 
myOtherEnvDir=paste0(myInputDir,'/Future_Env') 

# for using offsets; not yet done in BIEN
myRangePolyDir=NULL
mySamplingModelDir=NULL
mySamplingDataDir=NULL
myOffsetDirs=NULL

# system independent
otherDirs=list(
  rangePolyDir=NULL,
  rdistDir=paste0(baseDir,'/rDists'),
  domains=paste0(baseDir,'/domains'))
sortDirNames=c('Points','Bounding_Box','Convex_Hull','SDM','SDM10_20')
offsetDataDirNames=c('Expert_Maps')
samplingDataDirNames=NULL

allBaseDirs=sdmDirectories(baseDir,
                           warn=FALSE,
                           mySpeciesDir=mySpeciesDir,
                           myEnvDir=myEnvDir,
                           myOffsetDirs=myOffsetDirs,
                           mySamplingDataDir=mySamplingDataDir,
                           mySamplingModelDir=mySamplingModelDir,
                           myOtherEnvDir=myOtherEnvDir,
                           myCustomBackgroundDir=myCustomBackgroundDir,
                           myCustomBackgroundTable=myCustomBackgroundTable,
                           offsetDataDirNames=offsetDataDirNames,
                           samplingDataDirNames=samplingDataDirNames,
                           overwrite=FALSE,
                           sortDirNames=sortDirNames,
                           otherDirs=otherDirs)


#== 3. Prep environmental layers

source(paste0(myInputDir,'/Scripts/2BIENWorklow1_0_test_Make_Data.r'))
save(allBaseDirs,file=paste0(baseDir,'/allBaseDirs.rdata'))


#== 4. Sort species
### 4.a sort species by algorithm

sortDone=checkSortDone(allBaseDirs, deleteSorted=FALSE)
pointsProj=CRS("+init=epsg:4326")
sortSpeciesBulk(allBaseDirs,pointsProj,myprj=myprj,doThin=TRUE,thinCutoff=20,verbose=TRUE,overwrite=FALSE,doClean=TRUE)

### 4.b specify which species to run
speciesList=list.files(file.path(allBaseDirs$speciesDir,'SDM'),full.names=T)
done=checkSDMDone(allBaseDirs,speciesList) # check whether any already done
speciesList=done$notRun
str(done)

#== 5. Model settings

modelSettings=list()
modelSettings$samplingSettings=c('noBias','targetBG') 
modelSettings$expertSettings=list(prob=1e-6,rate=0,skew=1e-6,shift=0)
modelSettings$predictorSettings=NULL
modelSettings$regularizationSettings=NULL
modelSettings$priorSettings=NULL
modelSettings$backgroundSettings=NULL
modelSettings$algorithmSettings=c('maxnet')
modelSettings$formulaMaker="sdmGenericFormulas"
modelSettings$maxTime=500 # time for an individual call to glmnet()
modelSettings$samplingModel='none'

source(system.file("extdata/Demo_Workflow/Common_BIENWorkflow_Settings_v1.r", package='BIENWorkflow'))
if(Sys.info()['user']=='ctg') {
	source( '~/Dropbox/Projects/BIEN/BIENWorkflow/inst/extdata/Demo_Workflow/Common_BIENWorkflow_Settings_v1.r')
}

toDo$maxBGFit=3e4
toDo$otherEnvProjections=FALSE
toDo$plotOtherEnvPred=FALSE
toDo$makeBiasedBackground=TRUE
toDo$openFig=TRUE
toDo$whichFutures=NULL #c('he') # put anything here you could grep from the scenario name
toDo$whichFuturesToPlot=c('he')
toDo$plotBinaryShp=F
toSave$shapeFile=F
toDo$maxTrimDomainTime=60
# this could give you trouble; you might locate it with Sys.which('gdal_polygonize.py') or set toSave$shapefile=F; toDo$$plotBinaryShp=F
toDo$pypath="/Library/Frameworks/GDAL.framework/Versions/1.11/Programs/gdal_polygonize.py"
#on PC you probably should set toDo$evalFork=F
toDo$evalFork=F

### 6. Run Models

j=1; (speciesCSV=speciesList[j])

for (j in 1:length(speciesList)){
  print(j)
  out=sdmBIEN(speciesCSV=speciesList[j],
              allBaseDirs,
              modelSettings=modelSettings,
              toDo=toDo,
              toSave=toSave,
              toOverwrite=toOverwrite)
  gc()
}


```


```{r make presence files}
library(tidyverse) 

test_species <- read.csv("../Extra_SD_Data/sam_occurrences_171113.csv")
FamilyList <- read.csv("../Extra_SD_Data/APC_taxonlookup_Full_180201.csv")
i<- match(test_species$taxon, FamilyList$APC_name)
test_species$family <- FamilyList$family[i] 

species <- as.character(unique(test_species$taxon))
familys <- as.character(unique(test_species$family))

## get species files 
for (i in 1:length(species)){
  SP_1 <- test_species[test_species$taxon == species[i],]
  SP_2 <- SP_1[,2:3]
  name<- species[i] %>% str_replace_all(" ", "_") %>% paste0("Pres_Species/", .,".csv")
  write_csv(SP_2, c(name))
}

## Get Family files
for (i in 1:length(familys)){
  SP_1 <- test_species[test_species$family == familys[i],]
  SP_2 <- SP_1[,2:3]
  name<- familys[i] %>% str_replace(" ", "_") %>% paste0("Pres_Family/", .,".csv")
  write_csv(SP_2, c(name))
}

rm(species, familys, SP_1, SP_2, name, i) 
rm(test_species, FamilyList)
```

```{r prep climate data, echo=TRUE, eval=FALSE}
library(raster) 
library(rgdal)
library(stringr)
library(RCurl)
library(sp)
 
#Albers equal area projection
Albers<-CRS("+init=epsg:3577")
## MAsks
No_ocean <- raster("../Extra_SD_Data/Aus_masks/No_Ocean_50km.tif")
ausMaskE <- raster("../Extra_SD_Data/Aus_masks/Mask_Equal_50km.tif")

#make 100km equal area raster Albers equal area:
km50 <- raster(res = 50000, 
                xmn=-2904860, xmx=2695140,ymn=-5334205, ymx=-434205,
                crs ="+init=epsg:3577")
km1<-raster(res = 1000, 
            xmn=-2904860, xmx=2695140,ymn=-5334205, ymx=-434205,
            crs ="+init=epsg:3577")

#### Look at BIEN climate data
BIENclimate <- stack("../BIEN4_NCEAS_Test/Env_1_21_18/bien_v1_env.grd")
BIENclimate
BIENclimate$bio1
plot(BIENclimate$bio20)


#### Aridity
library(raster)
#### Crop Aridity Layer
aridity <- raster("../Extra_SD_Data/Global Aridity - Annual/AI_annual/ai_yr/w001001.adf")
ext<-extent(c(112,154.5,-44.475,-9.975))
aridity <- crop(aridity, ext)
plot(aridity)
writeRaster(aridity, "../Extra_SD_Data/Global Aridity - Annual/Aus_aridity.asc", crs = "+init=epsg:4326", overwrite=TRUE)

##Convert to equal areas
aridity <- raster("../Extra_SD_Data/Global Aridity - Annual/Aus_aridity.asc", crs = "+init=epsg:4326")
aridityAlbers <- projectRaster(aridity,km1,method='bilinear')
writeRaster(aridityAlbers, "../Extra_SD_Data/Global Aridity - Annual/Aus_aridity_Equal_1km.tif", overwrite=TRUE)

###Problem starts here
aridityAlbers<- raster("../Extra_SD_Data/Global Aridity - Annual/Aus_aridity_Equal_1km.tif")
aridity10 <- aggregate(aridityAlbers,10,'mean')
plot(aridity10)
writeRaster(aridity10, "Climate_data/Aus_aridity_Equal_10km.tif", overwrite=TRUE)

### Loop for climate data
layers <- list.files('../Extra_SD_Data/WorldClime/',full.names=T)
layers2 <- c('bio1','bio2','bio12','bio15','bio18','bio19','bio20')
for (i in 1:length(layers)){
  Bio_layer<- raster(layers[i])
  Bio_layer1 <- projectRaster(Bio_layer,km1,method='bilinear')
  Bio_layer2 <- aggregate(Bio_layer1,10,'mean')
  plot(Bio_layer2)
  writeRaster(Bio_layer2, paste0("Climate_data/Aus_", layers2[i], "_Equal_10km.tif"), overwrite=TRUE)
} 

bio12<-raster("Climate_data/Aus_bio12_Equal_10km.tif")
bio18<-raster("Climate_data/Aus_bio18_Equal_10km.tif") 
bio19<-raster("Climate_data/Aus_bio19_Equal_10km.tif")

### calculate cory's bio20
bio18_19 <- bio18/(bio18+bio19)
writeRaster(bio18_19, "Climate_data/Aus_bio18_19_Equal_10km.tif", overwrite=TRUE)
### similar variable using total precipitation
bio18_20 <- bio18/bio12
writeRaster(bio18_20, "Climate_data/Aus_bio18_20_Equal_10km.tif", overwrite=TRUE)


```

```{r Set Climate data, echo=TRUE, eval=FALSE}

# prep environmental layers (some of these are made below)
# get climate
cl.f=list.files('Climate_data/',full.names=T)
cl.f <- cl.f[c(1:5,9,11:15)]
cl=stack(cl.f)
names(cl)=c('aridity','bio1','bio12','bio15','bio20','bio2','bedrockDepth','bulkDensity1_4','clay1_4','ph1_4','silt1_4')
writeRaster(cl,file='Climate_data_final/Aus_bien_v1_env.grd',overwrite=T)
 

```

```{r Lookup table and all Pres, echo=TRUE, eval=FALSE}
#rm(list = ls())
library(tidyverse)
### List of Native Australian species
FamilyList <- read.csv("../Extra_SD_Data/APC_taxonlookup_Full_180201.csv")
All_species_list <- read.csv("../Extra_SD_Data/All_species_IDs_SCA_180215.csv")
All_species_list <- All_species_list[All_species_list$group == "native",]
Native_Species <- FamilyList[FamilyList$APC_name %in% All_species_list$canonicalName,]
rm(FamilyList, All_species_list)

#### Make the Lookup Table
Lookup_Table <- as.data.frame(Native_Species$order)
colnames(Lookup_Table) <- "order"
Lookup_Table$family <- Native_Species$family
Lookup_Table$genus <- Native_Species$genus
Lookup_Table$species <- Native_Species$APC_name %>% str_replace_all(" ", "_")
load("../Extra_SD_Data/Native_data_wide_1_180305.rds")
Growth_Form <- var_data_1[[1]]
i<- match(Native_Species$APC_name, Growth_Form$species_name)
Native_Species$growth_form <-Growth_Form$plant_growth_form[i]
Lookup_Table$growth_form <- Native_Species$growth_form
rm(var_data_1, i, Growth_Form)

### Get occurance data
Full_occur <- read_csv("../Extra_SD_Data/ALA_Native_With_Gridcell_SCA_180215.csv")
Full_occur <- Full_occur[Full_occur$scientificName %in% Native_Species$APC_name, ]
list <- c(unique(Full_occur$scientificName))
### Remove Species with no Occurance data
X <- Native_Species[Native_Species$APC_name %in% list,]
Lookup_Table <- Lookup_Table[Lookup_Table$species %in% X$new_name,]
rm(X)
Full_occur <- Full_occur[, c("longitude", "latitude", "family", "genus", "scientificName", "rank", "Grid_cell")]
gc()
write.csv(Lookup_Table,file='Scripts/Aus_lookup_Table.csv',row.names=F)

#### adapted From prep_target_groups_genus_v1.R
library(dplyr)
library(data.table)
library(doParallel)
genus= unique(Full_occur$genus) ## lookup table 2255 levels
genus_family = unique(Full_occur[,c('family','genus')])
family= unique(Full_occur$family) ## lookup table 307 levels

#All Species
Full_occur$species=gsub(' ','_',Full_occur$scientificName)
species= unique(Full_occur$species)
X <- Lookup_Table[Lookup_Table$species %in% species,]
rm(X)

#=============================================================================#write out family files
outdir.family="D:/Documents_2/SD_work/Aus_BIEN4_test/All_occurance/Aus_family_pres/"
if(!file.exists(outdir.family)) dir.create(outdir.family)

foreach(ii = 1:length(family)) %dopar% {
  out=subset(Full_occur,family==family[ii])[, c('longitude','latitude')]
  write.csv(out,file=paste0(outdir.family,family[ii],'.csv'),row.names=FALSE)
}

#=============================================================================#write out genus files
outdir.genus='D:/Documents_2/SD_work/Aus_BIEN4_test/All_occurance/Aus_Genus_Pres/'
if(!file.exists(outdir.genus)) dir.create(outdir.genus)

foreach(ii = 1:nrow(genus_family)) %dopar% {
  out=subset(Full_occur,family==genus_family[ii,1] & genus==genus_family[ii,2] )[,c('longitude','latitude')]
  write.csv(out,file=paste0(outdir.genus,paste0(genus_family[ii,], collapse='_'),'.csv'),row.names=FALSE)
}

#=============================================================================# write out species files
outdir.species="D:/Documents_2/SD_work/Aus_BIEN4_test/All_occurance/Aus_Species_pres/"
if(!file.exists(outdir.species)) dir.create(outdir.species)

foreach(ii = 1:length(species)) %dopar% {
  out=subset(Full_occur,species==species[ii])[, c('longitude','latitude')]
  write.csv(out,file=paste0(outdir.species,species[ii],'.csv'),row.names=FALSE)
}

#NEED TO, check the size number of samples per family and genus to see if there are any that will lead to trouble with target groups

```

```{r Test stuff, include=FALSE}
### are Aus Species in OFGS list?
FamilyList <- read.csv("../Extra_SD_Data/APC_taxonlookup_Full_180201.csv")
FamilyList$new_name <- FamilyList$APC_name %>% str_replace_all(" ", "_")
OFGS_list <- read.csv("../Extra_SD_Data/OFGS_Lookup_Table.csv")
overlap <- OFGS_list[OFGS_list$species %in% FamilyList$new_name,] # only about 800
rm(FamilyList, OFGS_list, overlap)
```

